name: localpipeline
services:
  servicebus:
    container_name: "servicebus"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    volumes:
      - "${CONFIG_PATH}:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
    environment:
      SQL_SERVER: sqledge  
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
    depends_on:
      - sqledge
    networks:
      sb-emulator:
        aliases:
          - "sb-emulator"
  sqledge:
        container_name: "sqledge"
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        networks:
          sb-emulator:
            aliases:
              - "sqledge"
        environment:
          ACCEPT_EULA: ${ACCEPT_EULA}
          MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
  webhook:
    build:
      context: .
      dockerfile: ScriptureRenderingPipeline/Dockerfile
    environment:
      - ServiceBusConnectionString="Endpoint=sb://servicebus;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
      - AzureWebJobsStorage="DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurestorage:10000/devstoreaccount1;QueueEndpoint=http://azurestorage:10001/devstoreaccount1;TableEndpoint=http://azurestorage:10002/devstoreaccount1;"
      - FUNCTIONS_WORKER_RUNTIME=dotnet
      - FUNCTIONS_EXTENSION_VERSION="~4"
      - FUNCTIONS_INPROC_NET8_ENABLED=1
    expose:
      - 8080:7071
    networks:
      - sb-emulator
    depends_on:
      - servicebus
  worker:
    build:
      context: .
      dockerfile: ScriptureRenderingPipelineWorker/Dockerfile
    environment:
      - ServiceBusConnectionString=Endpoint=sb://servicebus;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      - ScripturePipelineStorageConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurestorage:10000/devstoreaccount1;QueueEndpoint=http://azurestorage:10001/devstoreaccount1;TableEndpoint=http://azurestorage:10002/devstoreaccount1;
      - ScripturePipelineStorageOutputContainer="web"
      - ScripturePipelineStorageTemplateContainer="template"
      - AzureWebJobsStorage="DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurestorage:10000/devstoreaccount1;QueueEndpoint=http://azurestorage:10001/devstoreaccount1;TableEndpoint=http://azurestorage:10002/devstoreaccount1;"
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - FUNCTIONS_EXTENSION_VERSION="~4"

    networks:
      - sb-emulator
    depends_on:
      - servicebus
      - azurestorage
  azurestorage:
    container_name: "azurestorage"
    image: "mcr.microsoft.com/azure-storage/azurite:latest"
    volumes:
      - azurite:/data
networks:
  sb-emulator:
volumes:
  azurite: