version: '3.8'

services:
  webhook:
    build:
      context: .
      dockerfile: ScriptureRenderingPipeline/Dockerfile
    environment:
      - ServiceBusConnectionString=${ServiceBusConnectionString}
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
    ports:
      - "8004:8080"
