version: '3.8'

services:
  webhook:
    image: registry.walink.org/wa/scripturerenderingpipeline-webhook:latest
    environment:
      - ServiceBusConnectionString=${ServiceBusConnectionString}
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
    ports:
      - "8004:80"
