using System.Collections.Generic;
using System.Text.Json.Serialization;
using PipelineCommon.Models.Webhook;
using ScriptureRenderingPipeline.Models;

namespace ScriptureRenderingPipeline;

[JsonSerializable(typeof(BuildLog))]
[JsonSerializable(typeof(OutputIndex))]
[JsonSerializable(typeof(OutputBook))]
[JsonSerializable(typeof(OutputChapters))]
[JsonSerializable(typeof(WebhookEvent))]
[JsonSerializable(typeof(AppMeta))]
[JsonSerializable(typeof(DownloadIndex))]
[JsonSerializable(typeof(Dictionary<string,string>))]
/*
	 * This partial class contains a partial class that gets generated by the System.Text.Json source generator.
	 * Helps everything go faster since it doesn't need to do reflection at runtime.
	 */
internal partial class JSONContext: JsonSerializerContext
{
}