services:
  versereportingprocessor:
    image: wycliffeassociates/versereportingprocessor:${IMAGE_TAG}
    environment:
      - ConnectionStrings__ServiceBus
      - ConnectionStrings__Database
      - ConnectionStrings__BlobStorage
      - ConnectionStrings__Dataverse
      - MaxServiceBusConnections
      - APPLICATIONINSIGHTS_CONNECTION_STRING
