services:
  versereportingprocessor:
    image: wycliffeassociates/versereportingprocessor:${IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__ServiceBus
      - ConnectionStrings__Database
      - ConnectionStrings__BlobStorage
      - ConnectionStrings__Dataverse
      - MaxServiceBusConnections
