services:
  versereportingprocessor:
    image: wycliffeassociates/versereportingprocessor:${IMAGE_TAG}
    restart: unless-stopped
    environment:
      - ConnectionStrings__ServiceBus
      - ConnectionStrings__Database
      - ConnectionStrings__BlobStorage
      - ConnectionStrings__Dataverse
      - Gitea__Url
      - Gitea__User
      - Gitea__Password
      - MaxServiceBusConnections
      - EnableDatabasePush
      - EnablePortPush
      - APPLICATIONINSIGHTS_CONNECTION_STRING
